apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp
  annotations:
    # Disables http redirect to https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    app: webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: anyuzhang2018/flaskapp
        name: webapp
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: mongodb
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: user
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 5
